# -*- coding: utf-8 -*-
"""ProblemStatement3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WP-4AA1AT0yEXVKsIQYqizcKduQEbCq5
"""

import os
import datetime

os.chdir(r'C:\Users\tanma\OneDrive\Documents\office_work\')

dict={}
folders = ['odd_train', 'even_train']
files=[]

i=0
for r,d,f in os.walk(r'C:\Users\tanma\OneDrive\Documents\office_work\'):
  for file in f:
    dict[file]=os.path.join(r,file)
    files.append(file)
    i=i+1
  if (i==100):
    break

for folder in folders:
  if(not os.path.isdir(folder)):
    os.mkdir(folder)

for i in range(100):
  with open(files[i]) as file:
    data = file.read()
    ct = datetime.datetime.now().date()
    even_file_name= 'even_train\\' + files[i] + "_even_" + str(ct)
    odd_file_name= 'odd_train\\' + files[i] + "_odd_" + str(ct)
    even = open(even_file_name, 'w')
    odd = open(odd_file_name, 'w')
    line_count=1
    for line in data:
      if(line_count%2==0):
        even.write(line)
      else:
        odd.write(line)
      line_count=line_count+1
    even.close()
    odd.close()